#!/usr/bin/env node
/**
 * Compiles proto/prediction.proto for the Node.js gateway into shared/node/.
 *
 * The gateway loads the descriptor at runtime with @grpc/proto-loader, so the
 * two build outputs are:
 *   shared/node/prediction.proto  - the descriptor the gateway loads at runtime
 *   shared/node/types/*.ts        - protoc-derived TypeScript types for that
 *                                   descriptor, generated by proto-loader-gen-types
 *
 * The generated types are load-bearing: api/src/grpc-client.ts is typed against
 * ProtoGrpcType, so a proto change that the gateway does not account for fails
 * `pnpm build` at the tsc step rather than at runtime.
 */
import fs from "node:fs";
import path from "node:path";
import { ROOT, PROTO_DIR, PROTO_FILE, SHARED_NODE, run, step } from "./lib.mjs";

step("Compiling protobuf stubs for Node.js -> shared/node/");

fs.rmSync(SHARED_NODE, { recursive: true, force: true });
fs.mkdirSync(SHARED_NODE, { recursive: true });

// protoc (bundled with @grpc/proto-loader's codegen) -> TypeScript definitions.
const binExt = process.platform === "win32" ? ".cmd" : "";
const gen = path.join(ROOT, "node_modules", ".bin", `proto-loader-gen-types${binExt}`);
if (!fs.existsSync(gen)) {
  throw new Error(
    "proto-loader-gen-types not found. Run `pnpm install` at the repo root first.",
  );
}

const typesDir = path.join(SHARED_NODE, "types");

run(gen, [
  // These flags MUST mirror the protoLoader.loadSync() options in
  // api/src/grpc-client.ts. If they drift, the generated types describe a
  // different object shape than the loader actually produces at runtime.
  "--keepCase",
  "--longs=Number",
  "--enums=String",
  "--defaults",
  "--oneofs",
  "--json",
  "--grpcLib=@grpc/grpc-js",
  `--includeDirs=${PROTO_DIR}`,
  `--outDir=${typesDir}`,
  "prediction.proto",
]);

// proto-loader-gen-types emits `.ts` files containing nothing but types, using
// extensionless relative imports. Two post-processing passes make that output
// consumable from a strict NodeNext project:
//
//   1. `.ts` -> `.d.ts`, so tsc never tries to emit JavaScript for them (which
//      would otherwise put them outside api/'s rootDir).
//   2. extensionless relative imports -> `.js` specifiers, which NodeNext
//      requires and which resolve back to the sibling `.d.ts`.
function toDeclarationFiles(dir) {
  let converted = 0;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      converted += toDeclarationFiles(full);
      continue;
    }
    if (!entry.name.endsWith(".ts") || entry.name.endsWith(".d.ts")) continue;

    const rewritten = fs
      .readFileSync(full, "utf8")
      // strip the absolute host path protoc bakes into the header comment so
      // the generated tree is byte-identical across machines and CI
      .replace(PROTO_FILE, "proto/prediction.proto")
      .replace(/(from\s+')(\.\.?\/[^']*?)(')/g, (m, a, spec, b) =>
        /\.[a-z]+$/.test(spec) ? m : `${a}${spec}.js${b}`,
      );

    fs.writeFileSync(full.replace(/\.ts$/, ".d.ts"), rewritten);
    fs.rmSync(full);
    converted += 1;
  }
  return converted;
}

const converted = toDeclarationFiles(typesDir);
console.log(`  normalised ${converted} generated file(s) to .d.ts`);

// The gateway resolves the descriptor out of shared/ at runtime, so the
// generated tree is self-contained and the container image never needs /proto.
fs.copyFileSync(PROTO_FILE, path.join(SHARED_NODE, "prediction.proto"));

fs.writeFileSync(
  path.join(SHARED_NODE, "README.md"),
  [
    "# shared/node",
    "",
    "Generated by `pnpm run proto:node` (scripts/gen-node.mjs). Do not edit by hand;",
    "these files are gitignored and rebuilt on every `pnpm build`.",
    "",
    "- `prediction.proto` — descriptor copied from `/proto`, loaded at runtime by",
    "  `@grpc/proto-loader` in `api/src/grpc-client.ts`.",
    "- `types/` — TypeScript definitions emitted by `proto-loader-gen-types`.",
    "",
  ].join("\n"),
);

console.log(`  ok: ${converted} TypeScript definition file(s) + prediction.proto`);
