#!/usr/bin/env node
/**
 * Compiles proto/prediction.proto for the Python sidecar into shared/python/
 * using `python -m grpc_tools.protoc`.
 *
 * grpcio-tools ships its own protoc, so no system protoc install is required.
 * If the ambient interpreter does not already have grpcio-tools importable we
 * provision a throwaway venv under .venv/protoc and use that, which keeps
 * `pnpm build` working on a clean machine and inside the Docker builder stage.
 */
import fs from "node:fs";
import path from "node:path";
import { ROOT, PROTO_DIR, SHARED_PYTHON, run, tryRun, step } from "./lib.mjs";

// Pinned in lockstep with sidecar/requirements.txt: the generated *_pb2.py
// assert a minimum protobuf runtime version at import time, so a newer
// generator than the sidecar's runtime would fail at startup, not at build.
const GRPCIO_TOOLS = process.env.GRPCIO_TOOLS_VERSION ?? "grpcio-tools==1.83.0";

/** Find an interpreter that can `import grpc_tools`, provisioning one if needed. */
function resolvePython() {
  const explicit = process.env.PYTHON;
  const candidates = explicit
    ? [explicit]
    : ["python3", "python", path.join(ROOT, "sidecar", ".venv", "bin", "python")];

  for (const py of candidates) {
    if (tryRun(py, ["-c", "import grpc_tools"])) {
      console.log(`  using existing interpreter with grpcio-tools: ${py}`);
      return py;
    }
  }

  const venv = path.join(ROOT, ".venv", "protoc");
  const venvPython =
    process.platform === "win32"
      ? path.join(venv, "Scripts", "python.exe")
      : path.join(venv, "bin", "python");

  if (!tryRun(venvPython, ["-c", "import grpc_tools"])) {
    const base = candidates.find((py) => tryRun(py, ["--version"]));
    if (!base) throw new Error("no usable python interpreter found (tried: python3, python)");
    console.log(`  provisioning ${path.relative(ROOT, venv)} with ${GRPCIO_TOOLS}`);
    if (!fs.existsSync(venvPython)) run(base, ["-m", "venv", venv]);
    run(venvPython, ["-m", "pip", "install", "--quiet", "--upgrade", "pip"]);
    run(venvPython, ["-m", "pip", "install", "--quiet", GRPCIO_TOOLS]);
  }
  return venvPython;
}

step("Compiling protobuf stubs for Python -> shared/python/");

fs.rmSync(SHARED_PYTHON, { recursive: true, force: true });
fs.mkdirSync(SHARED_PYTHON, { recursive: true });

const python = resolvePython();

run(python, [
  "-m",
  "grpc_tools.protoc",
  `--proto_path=${PROTO_DIR}`,
  `--python_out=${SHARED_PYTHON}`,
  `--pyi_out=${SHARED_PYTHON}`,
  `--grpc_python_out=${SHARED_PYTHON}`,
  "prediction.proto",
]);

// grpc_tools emits `import prediction_pb2 as ...` (a flat, sys.path-relative
// import), so shared/python is put on sys.path rather than imported as a
// package. See sidecar/app/stubs.py.
fs.writeFileSync(
  path.join(SHARED_PYTHON, "README.md"),
  [
    "# shared/python",
    "",
    "Generated by `pnpm run proto:python` (scripts/gen-python.mjs) via",
    "`python -m grpc_tools.protoc`. Do not edit by hand; these files are",
    "gitignored and rebuilt on every `pnpm build`.",
    "",
    "This directory is placed on `sys.path` (see `sidecar/app/stubs.py`) because",
    "`prediction_pb2_grpc.py` imports `prediction_pb2` as a top-level module.",
    "",
  ].join("\n"),
);

const emitted = fs.readdirSync(SHARED_PYTHON).filter((f) => f !== "README.md");
console.log(`  ok: ${emitted.join(", ")}`);
